language: node_js
node_js:
    - "9"
    - "8"
    - "7"
    - "6"
after_success:
  if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "This will deploy!"
  else
    echo "This will not deploy!"
  fi
